# Introduction

We use this paper as support in order to prepare data sets: 


Yu, H., Sun, X., Thordarson, D.S., Solbakken, K., Solvang, W.D. (2024). A Network-Based Set Covering Model for Charging Station Location Problem: A Case Study in Norway. In: Wang, Y., Yu, T., Wang, K. (eds) Advanced Manufacturing and Automation XIII. IWAMA 2023. Lecture Notes in Electrical Engineering, vol 1154. Springer, Singapore. https://doi.org/10.1007/978-981-97-0665-5_26

In [23]:
import urllib.request
import requests
import json
import numpy as np

In [24]:
api_key = "AimWLdnm8TDPtAdj_QMmw4UCDjw4POCv0aQDKk7nsW4PVacVWv0d3WqI44eUlCJS"

# 1. Set up data and convert to JSON

https://learn.microsoft.com/en-us/bingmaps/rest-services/routes/calculate-a-distance-matrix?redirectedfrom=MSDN

(link to API documentation)

In [25]:
data = {
    "origins": [
    {"latitude": 68.57, "longitude": 14.91},
    {"latitude": 68.70, "longitude": 15.42},
    {"latitude": 68.62, "longitude": 15.65},
    {"latitude": 68.53, "longitude": 15.73},
    {"latitude": 68.42, "longitude": 15.99},
    {"latitude": 68.56, "longitude": 16.24},
    {"latitude": 68.63, "longitude": 16.59},
    {"latitude": 68.50, "longitude": 16.70},
    {"latitude": 68.53, "longitude": 16.99},
    {"latitude": 68.54, "longitude": 17.26},
    {"latitude": 68.55, "longitude": 17.56},
    {"latitude": 68.41, "longitude": 17.42},
    {"latitude": 68.91, "longitude": 15.10},
    {"latitude": 68.73, "longitude": 15.52},
    {"latitude": 68.09, "longitude": 13.23},
    {"latitude": 68.24, "longitude": 14.56},
    {"latitude": 69.25, "longitude": 17.95}
    ],
    "destinations": [
    {"latitude": 68.57, "longitude": 14.91},
    {"latitude": 68.70, "longitude": 15.42},
    {"latitude": 68.62, "longitude": 15.65},
    {"latitude": 68.53, "longitude": 15.73},
    {"latitude": 68.42, "longitude": 15.99},
    {"latitude": 68.56, "longitude": 16.24},
    {"latitude": 68.63, "longitude": 16.59},
    {"latitude": 68.50, "longitude": 16.70},
    {"latitude": 68.53, "longitude": 16.99},
    {"latitude": 68.54, "longitude": 17.26},
    {"latitude": 68.55, "longitude": 17.56},
    {"latitude": 68.41, "longitude": 17.42},
    {"latitude": 68.91, "longitude": 15.10},
    {"latitude": 68.73, "longitude": 15.52},
    {"latitude": 68.09, "longitude": 13.23},
    {"latitude": 68.24, "longitude": 14.56},
    {"latitude": 69.25, "longitude": 17.95}
    ],
    "travelMode": "driving"
}

dataset = json.dumps(data)

# 2. Request

See the link earlier for the structure

In [26]:
url = f"https://dev.virtualearth.net/REST/v1/Routes/DistanceMatrix?key={api_key}"

response = requests.post(url, data=dataset) # HTTP request

# 3. Print result

In [27]:
if response.status_code == 200:
    result = response.json() # need to parse to JSON response
    results = result['resourceSets'][0]['resources'][0]['results']
    for i in range (len(results)):
      indexDest = results[i]['destinationIndex']
      indexOrig = results[i]['originIndex']
      traveDist = results[i]['travelDistance']
      print(f"Distance between {indexOrig+1} and {indexDest+1} is {traveDist:.2f}.")
else:
    print("Error:", response.status_code)

Distance between 1 and 1 is 0.00.
Distance between 1 and 2 is 28.88.
Distance between 1 and 3 is 45.18.
Distance between 1 and 4 is 61.55.
Distance between 1 and 5 is 83.36.
Distance between 1 and 6 is 105.89.
Distance between 1 and 7 is 131.30.
Distance between 1 and 8 is 146.72.
Distance between 1 and 9 is 160.66.
Distance between 1 and 10 is 173.97.
Distance between 1 and 11 is 188.33.
Distance between 1 and 12 is 207.70.
Distance between 1 and 13 is 65.28.
Distance between 1 and 14 is 35.87.
Distance between 1 and 15 is 151.87.
Distance between 1 and 16 is 57.07.
Distance between 1 and 17 is 227.12.
Distance between 2 and 1 is 28.93.
Distance between 2 and 2 is 0.00.
Distance between 2 and 3 is 17.19.
Distance between 2 and 4 is 33.56.
Distance between 2 and 5 is 55.37.
Distance between 2 and 6 is 77.90.
Distance between 2 and 7 is 103.31.
Distance between 2 and 8 is 118.73.
Distance between 2 and 9 is 132.67.
Distance between 2 and 10 is 145.98.
Distance between 2 and 11 is 160.34

# 4. Distance matrix

In [28]:
if response.status_code == 200:
    result = response.json()
    results = result['resourceSets'][0]['resources'][0]['results']
    num_cities = 17
    distance_matrix = np.zeros((num_cities, num_cities))

    for i in range (num_cities):
      for j in range(num_cities):
          if i != j:
              traveDist = results[i * num_cities + j]['travelDistance']
              distance_matrix[i, j] = round(traveDist, 2)
else:
    print("Error:", response.status_code)

print(distance_matrix)

[[  0.    28.88  45.18  61.55  83.36 105.89 131.3  146.72 160.66 173.97
  188.33 207.7   65.28  35.87 151.87  57.07 227.12]
 [ 28.93   0.    17.19  33.56  55.37  77.9  103.31 118.73 132.67 145.98
  160.34 179.72  37.29   7.88 208.75 113.95 199.13]
 [ 45.24  17.21   0.    18.47  40.29  62.81  88.22 103.65 117.58 130.9
  145.25 164.63  52.59  20.89 193.66  98.86 212.14]
 [ 61.61  33.57  18.47   0.    21.81  44.34  69.75  85.17  99.11 112.42
  126.78 146.16  68.96  37.26 175.19  80.39 216.06]
 [ 83.42  55.39  40.29  21.82   0.    28.05  53.47  68.89  82.82  96.14
  110.5  129.87  90.77  59.08 194.07  99.27 199.78]
 [105.89  77.86  62.76  44.28  28.02   0.    25.41  40.83  54.77  68.08
   82.44 101.82 113.24  81.55 216.54 121.74 171.72]
 [131.4  103.36  88.26  69.79  53.53  25.5    0.    17.32  31.25  44.57
   58.93  78.3  138.75 107.05 242.05 147.25 152.73]
 [146.9  118.86 103.76  85.29  69.03  41.    17.43   0.    14.12  27.44
   41.8   61.17 154.25 122.55 257.55 162.75 173.44]
 [160.69 

# 5. Binary radius matrix
_Reminder : the binary matrix $a_{ij}$_ has a 1 on position $i,j$ if city $d(i,j)\leq r$ and has a 0 otherwise  

In [29]:
def create_radius_matrix(D, r):
    RM = np.zeros_like(D)
    for i in range(D.shape[0]):
        for j in range(D.shape[1]):
            if D[i, j] <= r:
                RM[i, j] = 1
    return RM

R = 130  # example radius used in Hao Yu's paper
radius_matrix = create_radius_matrix(distance_matrix, R)
print(radius_matrix)

[[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
